http:
  routers:
    placey-app:
      rule: "Host(`placey.eu`) || Host(`www.placey.eu`)"
      entryPoints:
        - websecure
      service: placey-app
      tls: {}
      priority: 1

    placey-webhook:
      rule: "Host(`placey.eu`) && PathPrefix(`/hooks/`)"
      entryPoints:
        - websecure
      service: placey-webhook
      tls: {}
      priority: 10

    placey-bucket:
      rule: "Host(`placey.eu`) && PathPrefix(`/bucket/`)"
      entryPoints:
        - websecure
      service: placey-bucket
      middlewares:
        - strip-bucket-prefix
      tls: {}
      priority: 10

  middlewares:
    strip-bucket-prefix:
      stripPrefix:
        prefixes:
          - "/bucket"

  services:
    placey-app:
      loadBalancer:
        servers:
          - url: "http://10.0.42.2:3000"

    placey-webhook:
      loadBalancer:
        servers:
          - url: "http://10.0.42.2:9100"

    placey-bucket:
      loadBalancer:
        servers:
          - url: "http://10.0.42.2:9000"
